#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys
import json
import subprocess
from optparse import OptionParser

    
def build():
    subprocess.call(["heroku", "login"])
    subprocess.call(["heroku", "create"])
    subprocess.call(["heroku", "addons:add", "mongohq"])
    ret = subprocess.check_output(["heroku", "info"])
    heroku_config = ret.split("\n")

    config = {}
    config["GIT_URL"] = heroku_config[2].split()[2]
    #config["REPO_SIZE"] = heroku_config[5].split()[2]
    config["WEB_URL"] = heroku_config[8].split()[2]

    with open("choucream.config", "w") as f:
        f.write(json.dumps(config, sort_keys=True, indent=4))
    
    

if __name__ == "__main__":
    parser = OptionParser()
    

    (options, args) = parser.parse_args()

    if len(args) < 1:
        print("Invalid arguments")

    if args[0] == "build":
        build()
    
    
